import { Activity, AlertTriangle, Banknote, CalendarCheck, CreditCard, TrendingUp, UsersRound, WalletCards } from "lucide-react";
import { AppShell, MetricCard, PageHeader } from "@/components/dashboard/app-shell";
import { DataTable, StatusPill } from "@/components/dashboard/data-table";
import { attendance, dashboardStats, money, payments, shortDate, trainers } from "@/lib/erp-data";

export default function DashboardPage() {
  const stats = dashboardStats();

  return (
    <AppShell>
      <PageHeader
        title="Dashboard"
        description="Live operating view for revenue, attendance, expiry risk, collections, expenses, and trainer output."
      />

      <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
        <MetricCard label="Today's revenue" value={money(stats.todayRevenue)} detail="Cash, MPESA, and bank collections" icon={Banknote} />
        <MetricCard label="Monthly revenue" value={money(stats.monthlyRevenue)} detail="Current month sample ledger" icon={TrendingUp} />
        <MetricCard label="Active members" value={String(stats.activeMembers)} detail={`${stats.expiredMembers} expired accounts`} icon={UsersRound} />
        <MetricCard label="Attendance today" value={String(stats.attendanceToday)} detail="Check-ins logged today" icon={CalendarCheck} />
      </section>

      <section className="mt-6 grid gap-4 lg:grid-cols-3">
        <div className="card p-5 lg:col-span-2">
          <div className="mb-4 flex items-center justify-between">
            <h3 className="text-lg font-black text-navy-950">Collections Mix</h3>
            <CreditCard className="h-5 w-5 text-teal-600" />
          </div>
          <div className="grid gap-3 sm:grid-cols-3">
            <div className="rounded-lg bg-slate-50 p-4">
              <p className="text-xs font-bold uppercase text-slate-500">Cash</p>
              <p className="mt-2 text-xl font-black text-navy-950">{money(stats.cash)}</p>
            </div>
            <div className="rounded-lg bg-teal-50 p-4">
              <p className="text-xs font-bold uppercase text-teal-700">MPESA</p>
              <p className="mt-2 text-xl font-black text-navy-950">{money(stats.mpesa)}</p>
            </div>
            <div className="rounded-lg bg-slate-50 p-4">
              <p className="text-xs font-bold uppercase text-slate-500">Bank</p>
              <p className="mt-2 text-xl font-black text-navy-950">{money(stats.bank)}</p>
            </div>
          </div>
          <div className="mt-4 grid gap-3 sm:grid-cols-2">
            <div className="rounded-lg border border-slate-200 p-4">
              <p className="flex items-center gap-2 text-sm font-bold text-slate-600">
                <WalletCards className="h-4 w-4 text-rose-500" />
                Expenses today
              </p>
              <p className="mt-2 text-2xl font-black text-navy-950">{money(stats.expenses)}</p>
            </div>
            <div className="rounded-lg border border-slate-200 p-4">
              <p className="flex items-center gap-2 text-sm font-bold text-slate-600">
                <Activity className="h-4 w-4 text-teal-600" />
                Net profit estimate
              </p>
              <p className="mt-2 text-2xl font-black text-navy-950">{money(stats.netProfit)}</p>
            </div>
          </div>
        </div>

        <div className="card p-5">
          <div className="mb-4 flex items-center gap-2">
            <AlertTriangle className="h-5 w-5 text-amber-500" />
            <h3 className="text-lg font-black text-navy-950">Expiry Alerts</h3>
          </div>
          <div className="space-y-3">
            {stats.expiryAlerts.slice(0, 6).map((member) => (
              <div key={member.id} className="rounded-lg border border-slate-200 p-3">
                <div className="flex items-center justify-between gap-2">
                  <p className="font-bold text-navy-950">{member.name}</p>
                  <StatusPill status={member.status} />
                </div>
                <p className="mt-1 text-xs text-slate-500">{member.membership_plan} expires {shortDate(member.expiry_date)}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      <section className="mt-6 grid gap-6 xl:grid-cols-2">
        <div>
          <PageHeader title="Recent Payments" description="Latest receipts generated by front desk and management." />
          <DataTable
            columns={["Receipt", "Member", "Plan", "Method", "Amount"]}
            rows={payments.map((payment) => [
              <span key="receipt" className="font-bold text-navy-950">{payment.receipt_number}</span>,
              payment.member_name,
              payment.membership_plan,
              payment.method,
              money(payment.amount)
            ])}
          />
        </div>
        <div>
          <PageHeader title="Trainer Performance" description="Revenue and commission output by trainer." />
          <DataTable
            columns={["Trainer", "Clients", "Revenue", "Commission"]}
            rows={trainers.map((trainer) => [trainer.name, trainer.active_clients, money(trainer.revenue), money(trainer.commission)])}
          />
        </div>
      </section>

      <section className="mt-6">
        <PageHeader title="Attendance Stream" description="Daily check-in and check-out activity with validity warnings." />
        <DataTable
          columns={["Code", "Member", "Check in", "Check out", "Status"]}
          rows={attendance.map((record) => [
            <span key="code" className="font-bold text-navy-950">{record.member_code}</span>,
            record.member_name,
            new Date(record.check_in_at).toLocaleTimeString("en-GB", { hour: "2-digit", minute: "2-digit" }),
            record.check_out_at ? new Date(record.check_out_at).toLocaleTimeString("en-GB", { hour: "2-digit", minute: "2-digit" }) : "Inside",
            <StatusPill key="status" status={record.status} />
          ])}
        />
      </section>
    </AppShell>
  );
}
